export const LOAD_SALES_HITS_REQ = 'LOAD_SALES_HITS_REQ';
export const LOAD_SALES_HITS_ERR = 'LOAD_SALES_HITS_ERR';
export const LOAD_SALES_HITS_OK = 'LOAD_SALES_HITS_OK';

export const LOAD_CAT_ITEMS_REQ = 'LOAD_CAT_ITEMS_REQ';
export const LOAD_CAT_ITEMS_ERR = 'LOAD_CAT_ITEMS_ERR';
export const LOAD_CAT_ITEMS_OK = 'LOAD_CAT_ITEMS_OK';
export const SET_OFFSET = 'SET_OFFSET';

export const LOAD_CAT_GROUPS_REQ = 'LOAD_CAT_GROUPS_REQ';
export const LOAD_CAT_GROUPS_ERR = 'LOAD_CAT_GROUPS_ERR';
export const LOAD_CAT_GROUPS_OK = 'LOAD_CAT_GROUPS_OK';
export const SET_CAT_GROUP = 'SET_CAT_GROUP';

export const LOAD_PROD_DATA_REQ = 'LOAD_PROD_DATA_REQ';
export const LOAD_PROD_DATA_ERR = 'LOAD_PROD_DATA_ERR';
export const LOAD_PROD_DATA_OK = 'LOAD_PROD_DATA_OK';

export const SIZE_SELECT = 'SIZE_SELECT';
export const QUANTITY_SELECT = 'QUANTITY_SELECT';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'ADD_ITEM_TO_CART';
